### ISSUE TITLE
Server side rendering is broken 

### ISSUE THREAD

**Issue by jakimarks** [adobe-webplatform/balance-text#123]
Seems like SSR is not supported in the current state.
[This code](https://github.com/adobe-webplatform/balance-text/blob/dd7c252fcb3f62c4c9f1c2ad5663d42b75cb5af2/balancetext.js#L170) is not SSR safe. It should probably look like this:
```java
function hasTextWrap() {
       if (typeof window === 'undefined') {
            return false;
        }
        var style = document.documentElement.style;
        return style.textWrap || style.WebkitTextWrap || style.MozTextWrap || style.MsTextWrap;
    }
```

I would have opened a PR but this project is using jslint and it complains about it:
```
#1 Unexpected 'typeof'. Use '===' to compare directly with undefined.
```
But in this case it has to be checked like this because the `window` variable will not be declared at all for SSR. And I couldn't make the linter ignoring this line.
Would be good to make this work again for SSR as soon as possible.

**Comment by redmunds** [comment]
That seems like overkill to determine if `window` object exists. Will this simplified code work?

```
function hasTextWrap() {
       if (!window) {
            return false;
        }
        var style = document.documentElement.style;
        return style.textWrap || style.WebkitTextWrap || style.MozTextWrap || style.MsTextWrap;
}
```

**Comment by jakimarks** [comment]
My preference would have been as well to get rid of the lint violation by actually resolving the violation. But this check is in this case the only check that will actually work, because both 
```java
if (window === undefined) …
``` 
and  
```java
if (!window) …
```
do both throw an error (because `window` is not declared in case of server side rendering):

```
/Users/jmarks/Documents/godfathers/apollonia/node_modules/balance-text/balancetext.js:170
        if (!window) {
        ^

ReferenceError: window is not defined
    at hasTextWrap (/Users/jmarks/Documents/godfathers/apollonia/node_modules/balance-text/balancetext.js:170:9)
    at /Users/jmarks/Documents/godfathers/apollonia/node_modules/balance-text/balancetext.js:773:9
    at /Users/jmarks/Documents/godfathers/apollonia/node_modules/balance-text/balancetext.js:70:26
    at Object.<anonymous> (/Users/jmarks/Documents/godfathers/apollonia/node_modules/balance-text/balancetext.js:74:2)
```

**Comment by jakimarks** [comment]
Seems like there was a [similar issue](https://github.com/Khan/react-balance-text/issues/1) in the beginning that was fixed. Due to changes or refactoring this check was removed so that SSR is again not feasible anymore.

**Comment by redmunds** [comment]
As you can tell from my previous comment, I'm not familiar with server side rendering. After looking through the references you pointed out, this change makes sense.

I don't see a way to make JSLint accept this code (without accepting all globals), so I guess it's time to upgrade to eslint.

**Comment by redmunds** [comment]
Fixed. PRs #124, #125
