### ISSUE TITLE
Has no effect in Firefox

### ISSUE THREAD

**Issue by ashleedawg** [adobe-webplatform/balance-text#146]
Based on the [demo page](https://rileyjshaw.com/balance-text/demo/index.html), this has no effect in Firefox.

As per the instructions on the demo page, I tried resizing the browser window, and changing the font size (Ctrl +/-) several times, and refreshed the page between changes, but both the "left" and "right" sample texts remained identical in all cases.

![screenshot](https://user-images.githubusercontent.com/29980309/137640114-3ee88f22-88b6-4530-820d-a2699c325a9d.png)

Firefox is updated to **93.0 (64-bit)** (October 5, 2021).

**Comment by redmunds** [comment]
@ashleedawg Where did you find that link? It points to https://rileyjshaw.com/balance-text/demo/index.html 
cc: @rileyjshaw 

That page is broken in all browsers for me. This is what I see in console:
```
Mixed Content: The page at 'https://rileyjshaw.com/balance-text/demo/index.html' was loaded over HTTPS, but requested an insecure script 'http://use.edgefonts.net/source-sans-pro:n3,n4,i3,i4,n6.js'. This request has been blocked; the content must be served over HTTPS.
```

This is link to demo page from this repo: https://opensource.adobe.com/balance-text/demo/index.html
Which seems to be working.
