### ISSUE TITLE
Causes screen to jump back to balanced text after scrolling down

### ISSUE THREAD

**Issue by jamminjames** [adobe-webplatform/balance-text#153]
### Expected Behaviour
After scrolling down past balanced text, it should stay there.
### Actual Behaviour
Jumps back up to text after scrolling down, sometimes . If it doesn't the first time, then it will if you start to scroll back up slightly. (Eg, scroll down well past balanced text, then scroll up a few pixels. Jumps all the way back up to beginning of balanced text.)

#### Steps to Reproduce
Scroll down.
#### Platform and Version
Most recent balancetext.min.js, Viewing page in most recent Google Chrome on Android 11.0 tablet. (Doesn't seem to happen on a Windows desktop).

**Comment by redmunds** [comment]
This is the first I've heard of this issue. Can you provide a link to a page that has this problem? I currently don't have access to an Android 11.0 Tablet, but I can try on some other devices. Maybe someone else can help verify?

**Comment by jamminjames** [comment]
Here's a page with it. Sometimes you have to scroll up and down a time or two before it happens:
https://subs.humortimes.com/subs-ht.php

It's actually an Android 11 phone I'm using to test. I suspect it happens on other Android versions as well.

**Comment by jamminjames** [comment]
Has anyone else seen this behavior while viewing the link I gave? I'm going to stop using it soon if it can't be fixed, so as not to frustrate users. But I wanted to leave it up for a bit, so you can see it. @redmunds ?

**Comment by jamminjames** [comment]
@redmunds Please let me know when you can look at it on an Android, I'll put the js file back in. I really want to use it, but the jumping around problem is not good for users.

**Comment by jamminjames** [comment]
@redmunds Update: I am leaving up a test page, so you can check out the behavior: https://subs.humortimes.com/subs-ht-test.php

Scroll down past the form, and it'll jump back up to the middle of the form. Sometimes you have to start scrolling up a bit for the jump to happen. It only happens when balancetext.min.js is loaded.

**Comment by jamminjames** [comment]
@redmunds Have you had an opportunity to look at this? Seems like something that could affect a lot of users. It could also be something that's not noticed by website authors that use the js. I didn't notice it for a long time.

**Comment by redmunds** [comment]
Sorry, I haven't had a chance to look at it (too busy with day job).

I'm guessing that it only happens if you scroll page immediately after opening it (i.e. after initial render, but before `balanceText` has executed. Does that sound about right? Maybe you're seeing it more than others because your page is larger and/or more complex than most pages.

A reasonable fix may be to store current `scrollPos` before `balanceText` executes, and then restoring it afterwards. Can you try that to see if it fixes your problem? If so, I can try to incorporate that fix into this project. Thanks.

**Comment by redmunds** [comment]
Looks like balance text functionality is getting close to being supported in Chrome, so hopefully we won't need this code for much longer:
https://twitter.com/intenttoship/status/1622936718604218369

**Comment by jamminjames** [comment]
Okay, maybe not worth it then. But just for the record, it's not after it's executed. However, I realized it does seem to happen just as you're scrolling to a second set of balanceText text, after it's executed in the previous text above the form. So, maybe that's a clue. Does it execute as you scroll, or is all the text affected before you scroll? Is it trying to reload? Is there a way to stop that? Or is that basically the same as what you're talking about?

Regarding restoring position, though, doesn't your script already do that with `el.style.position = oldPosition;`?

**Comment by jamminjames** [comment]
Okay, I think I've got it. This seems to work:

Near the top of the balanceText function (just inside of `function balanceText(elements) {`), put:
`var scrollPos = window.pageYOffset;`

Or maybe, to make sure it'll work on most browsers, you could do this, but I think `window.pageYOffset` is pretty safe across browsers. I'm using the above, and it's working on my Android Chrome browser.
`var scrollPos = window.pageYOffset || window.scrollTop || document.getElementsByTagName("html")[0].scrollTop;`

And just before the close of the function (under `el.style.lineHeight = oldLH;`):
`window.scrollTo(0, scrollPos);`
