### ISSUE TITLE
Adds `<br data-owner="balance-text" aria-hidden="true">` before text

### ISSUE THREAD

**Issue by therealgilles** [adobe-webplatform/balance-text#154]
### Expected Behaviour
The library should never add `<br>` before the text.

### Actual Behaviour
The library adds `<br data-owner="balance-text" aria-hidden="true">` before the text some times.

#### Steps to Reproduce
Not sure yet.

#### Platform and Version
Platform: Ubuntu 18.04
Library version: 3.3.1

**Comment by therealgilles** [comment]
Should there be a check for `splitIndex` being 0 here?
https://github.com/adobe/balance-text/blob/0f0826f7a9933cdb478cacea99196e4b874bfd0d/balancetext.js#L608

doing this:
```JS
    if (splitIndex === 0) break;
```

**Comment by therealgilles** [comment]
I think the problem is happening because the guess index falls exactly on a blank space. Digging...

**Comment by therealgilles** [comment]
It looks like my problem is that I was trying to apply text balancing on an h2 tag but it only works properly with p or span. Am I correct?

**Comment by therealgilles** [comment]
Ah never mind, I found the problem. The h2 tag has a `width: 100%` prop which messes up the text width calculation.

**Comment by redmunds** [comment]
Thanks for detailed problem and solution! Glad you figured it out.
