### ISSUE TITLE
Tag New Versions

### ISSUE THREAD

**Issue by TuckerWhitehouse** [adobe-webplatform/balance-text#40]
Hey, Looks like the latest version wasn't tagged, would you mind doing so, similar to the discussion in #30.

**Comment by redmunds** [comment]
@TuckerWhitehouse I setup this repo for auto-update of these CDNs, so newer versions are now available:

* https://cdnjs.cloudflare.com/ajax/libs/balance-text/1.6.0/jquery.balancetext.min.js
* https://cdn.jsdelivr.net/jquery.balancetext/1.6.0/jquery.balancetext.min.js

Do you have a similar auto-update mechanism?

**Comment by TuckerWhitehouse** [comment]
@redmunds The setup I have currently requires that I update a config file each time I want to add a new version of a library, and then pulls from GitHub tags. I have been working on an update that would keep itself updated based on GitHub tags/releases but I've found myself more frequently using npm and packaging all of my scripts locally. Thanks!
