### ISSUE TITLE
angularjs version of balance-text?

### ISSUE THREAD

**Issue by rwillmer** [adobe-webplatform/balance-text#49]
I'd like to make a non-jquery AngularJS version of this, based on your code.

Any objections? I've just read through the Apache licence and I think it says I can do that. 

P.S.  Thanks for sharing this plugin, I _really_ love it.

**Comment by redmunds** [comment]
@rwillmer That would be great! I figured most people were already using jQuery, so I used it to reach as many browsers as possible. Please send me a link so we can cross-reference these solutions.

FYI, I originally wrote this to illustrate feature when I proposed it to w3c css-text module (and it's finally been added as [`text-wrap: balance`](http://dev.w3.org/csswg/css-text-4/#text-wrap)), so hopefully we won't need this polyfill much longer.

**Comment by rwillmer** [comment]
Great, thanks for your support!

**Comment by bfred-it** [comment]
Once #63 is merged I'll be working on a non-jQuery version so it can just be used with anything.

**Comment by rileyjshaw** [comment]
@bfred-it any progress on the non-jQuery version? Lots of interest at my office.

**Comment by bfred-it** [comment]
Not really, #63 is still open and I'm not available to maintain a fork.

**Comment by JohnnyTheTank** [comment]
well, I wrote an angularjs wrapper: https://github.com/JohnnyTheTank/angular-balance-text

**Comment by BrianGenisio** [comment]
@bfred-it I've created the non-jQuery version and added a small jQuery wrapper around it, FYI: https://github.com/adobe-webplatform/balance-text/pull/95

**Comment by redmunds** [comment]
@rileyjshaw A non-jQuery version PR from @BrianGenisio is up at #95 if you care to try it out.

**Comment by rileyjshaw** [comment]
@redmunds I saw! Very _very_ excited about that. @BrianGenisio is a coworker of mine :)

**Comment by redmunds** [comment]
@rwillmer Balance-text 3.0.0 no longer has a jQuery requirement, so I should be easy to use with Angular. Is there any need to keep this issue open?

**Comment by redmunds** [comment]
Closing.
