### ISSUE TITLE
make work when flex box is involved

### ISSUE THREAD

**Issue by mkstix6** [adobe-webplatform/balance-text#51]
Is anyone else having issues when flex box is also used on the .balance-text element or parents that control it's width?

**Comment by redmunds** [comment]
I haven't heard anyone report that. Can you provide an example?

**Comment by mkstix6** [comment]
K cool. I'll look at making a codepen soon. Could just be something I messed up.

**Comment by redmunds** [comment]
Closing until I receive more info.

**Comment by spinboxnl** [comment]
Hi Redmunds,

This problem occurs when the .balance-text element is a direct child of a flexbox element.

The following code causes the width to be not correct and the code not to be executed. I guess `display:inline;` and `position:static` still has max-width of the flexbox. Changing this to `block` and `absolute` fixed it, but I didn't test if it breaks anything else.

`            // temporary settings
            $this.css({
                'white-space': 'nowrap',
                'float': 'none',
                'display': 'inline',
                'position': 'static'
            });`

I myself fixed this issue by adding a block element as the direct child. Thanks for your work!

**Comment by redmunds** [comment]
@spinboxnl Thanks for the detailed followup. This can't be made as a global change -- see discussion in #75. But, I'll keep this case in mind with future changes.

**Comment by bfred-it** [comment]
A solution for this one might be using [selections](http://stackoverflow.com/questions/12603397/calculate-width-height-of-the-selected-text-javascript) to calculate the necessary width, instead of removing the text. This would be a near-total rewrite.
