### ISSUE TITLE
Newly added elements aren't balanced

### ISSUE THREAD

**Issue by rileyjshaw** [adobe-webplatform/balance-text#56]
Hi @redmunds!

I came across this while working on a PR for #55 and thought it deserved its own discussion.

With the current API ( `$('.selector').balanceText()` ), we balance only the current matching elements on the page. Any elements matching this selector that are added afterward are not balanced (on `resize`, subsequent calls to `balanceText`, etc). This is not how CSS rules generally work.

This is also different from how elements with a `.balance-text` class are treated. Whether they were added before or after balanceText was instantiated, they are still included in balancing since [a fresh search is made at runtime](https://github.com/adobe-webplatform/balance-text/blob/07754ac23f7a5f36cc62033ea26efefde0fe09cc/jquery.balancetext.js#L412).

I think that we should employ the method used by `.balance-text` across the board by keeping a list of selectors that should be balanced. I'm happy to take a first pass at this in a PR, but wanted your thoughts first.

Before I fix #55, we should come to a decision on the expected behaviour here.

**Comment by redmunds** [comment]
@rileyjshaw Thanks for looking into this.

The way I was thinking about solving #55 is basically what you mentioned: to allow registering of selectors (other than `.balance-text` which should be automatically registered to maintain current behavior). Can you think of a method name more elegant than `balanceTextRegisterSelector()` ?

Do you know of a good way to listen for page contents being updated to re-balance text? I'm thinking it would be enough to expose the `applyBalanceText()` method so page authors could call it when necessary. Maybe `balanceTextApply()` or `balanceTextUpdate()` would be more consistent with other method names. Thoughts?

**Comment by rileyjshaw** [comment]
We might be able to keep the same API, and just have `$('el').balanceText()` add that selector to the watchlist by default. I can have a prototype of that behaviour by the end of the night. Alternatively, we could switch the usage to `$.balanceText('el')`... but either way I don't think we need to expose an additional function for registering selectors, it should just happen by default. Thoughts?

I'll look into watching for changes, but I think that exposing a `balanceTextUpdate()` function is the best way to go - having a listener fire for every DOM change might be excessive.

**Comment by redmunds** [comment]
Automatically registering the selector via `$('el').balanceText()` would be awesome!

**Comment by rileyjshaw** [comment]
Cool :) I'm on it

**Comment by rileyjshaw** [comment]
So sorry for the delay. I've addressed this in https://github.com/adobe-webplatform/balance-text/pull/58, let me know what you think!

**Comment by redmunds** [comment]
This is fixed by https://github.com/adobe-webplatform/balance-text/pull/58. Closing.

**Comment by redmunds** [comment]
Re-opening. I forgot about `balanceTextUpdate()` which is pending in #61.

**Comment by redmunds** [comment]
Now it's fixed. Closing.
