### ISSUE TITLE
Balance-text crashes browser when trying to split long URL strings

### ISSUE THREAD

**Issue by netes** [adobe-webplatform/balance-text#69]
Hi,
First of all, thanks for great plugin! Unfortunately, I've got some issue with it.
Recently I noticed that when `balance-text` is trying to balance line with long URL strings it crashes the browser, here you can check it:
http://jsbin.com/wipirumiwa/edit?html,js,output

Just add class `balance-text` to the div with urls and the browser will crash.
Do you have any idea how to fix this?

Regards,
Kamil

**Comment by redmunds** [comment]
@netes Thanks for reporting bugs. I created a local page, added `balance-text` class to the div, and opened it up in Firefox, Chrome, and IE on Win7 and none of them crashed.
What OS & version are you using?
Also let me know which browsers the you see the crash in (or not).

**Comment by netes** [comment]
@redmunds sorry, I put wrong link in first message, here's fixed:
http://jsbin.com/wipirumiwa/edit?html,js,output

To reproduce you only have to add `-text` to the class of the `div` in jsbin.
It crashes in FF, Chrome and Safari, all of them on OSX.

**Comment by netes** [comment]
Little update: it seems that this bug has something to do with container width units.
I made a local version for testing and here what I found:
When I use `px` for container width - everything works fine, but if I change `px` to percentages - it crashes the browser. Don't really know why on JSBin it crashes the browser even without specifying width of container, but if we do that, and use `px` it won't crash.

**Comment by netes** [comment]
Seems that I found a solution and width was not a problem. Particular width could crash browser but the real cause is different. I figured out that script crashes when `txt` variable is empty string. If it's empty `index` value goes down from `-1` to infinity which causes browser crash (infinite loop). To fix it I just added `if (txt !== '') {` before the `for` loop:

```javascript
        if (txt !== '') {
          for(;;) {
              while (!isBreakOpportunity(txt, c)) {
                  c += dir;
              }

              $el.html(txt.substr(0, c));
              w = $el.width();

              if ((dir < 0)
                      ? ((w <= desWidth) || (w <= 0) || (c === 0))
                      : ((desWidth <= w) || (conWidth <= w) || (c === txt.length))) {
                  break;
              }
              c += dir;
          }
        }
```

Seems that everything's working fine.

**Comment by redmunds** [comment]
Thanks for investigating. I'll have some time next week to review your fix.

**Comment by redmunds** [comment]
Closing as Fixed. Note that I have not yet updated CDN version -- I'm waiting for a couple unresolved PRs.

**Comment by netes** [comment]
Great, thanks!
