### ISSUE TITLE
AngularJS Wrapper

### ISSUE THREAD

**Issue by JohnnyTheTank** [adobe-webplatform/balance-text#81]
I've created an AngularJS Wrapper for your jQuery plugin: https://github.com/JohnnyTheTank/angular-balance-text
is there any wish open?

**Comment by redmunds** [comment]
@JohnnyTheTank Nice!

> is there any wish open?

It looks like you found open issue #49 which is about having a non-jQuery version. I notice that your demo page includes jQuery. Is jQuery still required for your plugin,m or is that an oversight?

**Comment by JohnnyTheTank** [comment]
it's just a wrapper. you still need jquery and your plugin as dependecy
