### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by kevinmickey** [adobe-webplatform/balance-text#84]
See https://docs.npmjs.com/getting-started/publishing-npm-packages

**Comment by alanwillms** [comment]
Same issue here:

```
npm install --save balance-text
....
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/balance-text
npm ERR! 404 
npm ERR! 404  'balance-text' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

**Comment by bfred-it** [comment]
It's there now: https://www.npmjs.com/package/balance-text

It uses `window.jQuery`, so require it this way:

```js
window.jQuery = require('jQuery')l
require('balance-text');
```

I can pass the npm name to Adobe once they decide to support it officially, until then at least it's usable. Ping me here if a new version comes out

**Comment by bfred-it** [comment]
<img width="320" alt="v3 published" src="https://cloud.githubusercontent.com/assets/1402241/21742988/8165a990-d4ae-11e6-8a82-44fa936250d3.png">

**Comment by redmunds** [comment]
Note to self: add reference and link to npm module in README (also vanity page).

**Comment by bfred-it** [comment]
```sh
❯ npm publish
+ balance-text@3.1.0
```

**Comment by redmunds** [comment]
@bfred-it Please update npm for v3.1.1

**Comment by bfred-it** [comment]
```
❯ npm publish
+ balance-text@3.1.1
```

**Comment by bfred-it** [comment]
If you have an npm user I can [add you as an owner](https://docs.npmjs.com/cli/owner) of the package and if you prefer you can also [automate the publishing via travis](https://docs.travis-ci.com/user/deployment/npm/)

**Comment by redmunds** [comment]
My (newly created) npm id is `redmunds-adobe`. You're welcome to automate it, but either way works for me.

**Comment by bfred-it** [comment]
```
❯ npm owner add redmunds-adobe
+ redmunds-adobe (balance-text)
```

I believe you are now able to run `npm publish` or, my favorite, [`np`](https://github.com/sindresorhus/np)` && `[`release`](https://github.com/zeit/release)
