### ISSUE TITLE
update jquery dependency

### ISSUE THREAD

**Issue by kevinmickey** [adobe-webplatform/balance-text#85]
> npm WARN deprecated jquery@1.8.3: Versions of the jquery npm package older than 1.9.0 are patched versions that don't work in web browsers. Please upgrade to >=1.11.0.

Consider using a range like "jquery": "1.9.1 - 3"

**Comment by redmunds** [comment]
@kevinmickey Thanks for the head's up. I posted a fix in PR #88. Does that fix issue?

Note that minified version has not yet been updated. I'll update that with next rev (1.7.0).

**Comment by kevinmickey** [comment]
Yup, that looks good - thanks!
