### ISSUE TITLE
Recalculate on Window Resize doesn't work in Chrome Mac OSX

### ISSUE THREAD

**Issue by christianmagill** [adobe-webplatform/balance-text#91]
I'm having an issue where Balance Text fails to recalculate on window resize, Chrome Mac OSX.

I've tried downloading through Bower and using the CDN as well. 

http://codepen.io/christianmagill/pen/akVxYP

![screen shot 2016-07-13 at 3 19 06 pm](https://cloud.githubusercontent.com/assets/2133370/16816751/7521f3dc-490d-11e6-85b0-fe76331175fc.png)

**Comment by redmunds** [comment]
Sorry, it looks like the README.md is out-of-date. To automatically update on resize using version 2, use:

```js
    $.balanceText('h1');
```

Does that fix it?

**Comment by redmunds** [comment]
No response from bug filer. Closing.
