### ISSUE TITLE
$.balanceTextUpdate() should be $.fn.balanceTextUpdate()?

### ISSUE THREAD

**Issue by jab** [adobe-webplatform/balance-text#92]
The README says to call `$.balanceTextUpdate()` to manually re-balance all triggered elements, but that causes `Uncaught TypeError: $.balanceTextUpdate is not a function(…)`. Changing this to `$.fn.balanceTextUpdate()` seems to do the trick.

**Comment by redmunds** [comment]
@jab Thanks. Fixed.

**Comment by jab** [comment]
Thanks for [fixing](https://github.com/adobe-webplatform/balance-text/commit/2c6f1f5aff8e461be586642ec8c2287cc85097c7), for the other docs improvements, and for balance-text in general, @redmunds. Hope efforts to get this into the CSS spec are going well.

**Comment by jab** [comment]
By the way, I was seeing balance-text not working in my (Polymer-using) web app when testing in mobile Chrome and Safari on my iPhone (running latest iOS 9.3.3) in many cases *until* I added a call to `$.fn.balanceTextUpdate()` in a `'WebComponentsReady'` event listener. (This problem did *not* occur in Chrome or Safari on latest OS X.) Seems worth documenting this so other users are aware of it, and if this is not expected behavior, I'd be happy to file another issue for fixing it.

**Comment by redmunds** [comment]
@jab Interesting. Yes, please open a new issue for that.

**Comment by jab** [comment]
Please see #93, which includes a link to a minimal test case. In creating that, I realized the problem actually reproduces on desktop too.
