### ISSUE TITLE
Bad committer info

### ISSUE THREAD

**Issue by BrianGenisio** [adobe-webplatform/balance-text#98]
Looks like all of my commits had a bad email reference.  It means the history of this repo aren't lining up with a real person (gmail.org instead of gmail.com... oops!).  I don't know how it happened.  If you don't mind, it is relatively easy to fix... you run the following script on the repo:

```sh
#!/bin/sh

git filter-branch --env-filter '

OLD_EMAIL="briangenisio@gmail.org"
CORRECT_NAME="BrianGenisio"
CORRECT_EMAIL="briangenisio@gmail.com"

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_COMMITTER_NAME="$CORRECT_NAME"
    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
    export GIT_AUTHOR_NAME="$CORRECT_NAME"
    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
```

And then you push the changes.

```sh
git push --force --tags origin 'refs/heads/*'
```

I got the instructions on how to fix it from [Github's help site](https://help.github.com/articles/changing-author-info/) and I ran it on my [other repo](https://github.com/Khan/react-balance-text) to fix the problem there as well [our fork of your repo.](https://github.com/Khan/balance-text/commits/master)  If you don't want to do this kind of surgery on your repo, I understand.  Just figured I'd throw it out there.

**Comment by redmunds** [comment]
Oh, I was wondering about that. Fixed. Thanks!

**Comment by BrianGenisio** [comment]
Thanks!
